### ISSUE TITLE
Using In React

### ISSUE THREAD

**Issue by kpguru20001** [JoanClaret/html5-canvas-animation#10]
Hi i am actually struggling to find a way to use this file in react how do i do soo

**Comment by 542869246** [comment]
The mobile side cannot be dragged.
It will report an error: 3d-lines-animation.js:133 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
`event.preventDefault();`
then,just delete this line
