### ISSUE TITLE
Page can't scroll on mobile phones.

### ISSUE THREAD

**Issue by ty0x2333** [JoanClaret/html5-canvas-animation#2]

**Comment by CrisDev93** [comment]
Using 3d-lines-animation.js example, when you run the page in a mobile, just comment the next lines ->

```
//   document.addEventListener( 'touchstart', onDocumentTouchStart, false );
//   document.addEventListener( 'touchmove', onDocumentTouchMove, false );
```

 OR instead of comment the lines I have used this project for detect if the current device is a phone or computer https://github.com/arasatasaygin/is.js , this can help you also, when you dectecs that is not a phone you can enable the touchstart and touchmove listeners. 

:+1:
